drop table Clientes cascade constraints purge;
drop table Cartao_debito cascade constraints purge;
drop table Cartao_Credito cascade constraints purge;
drop table Conta_Corrente cascade constraints purge;
drop table Conta_Poupanca cascade constraints purge;
drop table Documento_Conta cascade constraints purge;
drop table Emprestimos cascade constraints purge;
drop table Financiamentos cascade constraints purge;
drop table Maquininha cascade constraints purge;
drop table PIX cascade constraints purge;
drop sequence seq_cartao_credito;
drop sequence seq_cartao_debito;
drop sequence seq_clientes;
drop sequence seq_conta_corrente;
drop sequence seq_conta_poupanca;
drop sequence seq_documento_conta;
drop sequence seq_emprestimos;
drop sequence seq_financiamento;
drop sequence seq_maquininha;
drop sequence seq_pix;
